env:
  # ブラウザで使用するのでbrowserとes2021をONにしておく
  browser: true
  es2021: true

# Vueを読み込めるようにする。eslint-plugin-vueが提供してくれている
parser: "vue-eslint-parser"

parserOptions:
  # VueをTypescriptで使う場合は指定する必要がある。vue-eslint-parser固有のオプション
  parser: "@typescript-eslint/parser"
  # ES Modulesを使ってコードを書く場合はmoduleを指定する必要がある
  sourceType: module

plugins:
  # eslint-plugin-vueが提供してくれているルールを追加する
  - vue

# パッケージが提供してくれているおすすめ設定を使う設定
extends:
  # eslintが提供してくれている設定
  - "eslint:recommended"
  # eslint-plugin-vueが提供してくれている設定
  - "plugin:vue/vue3-recommended"
  # typescriptを使用する場合は追加
  - "@vue/typescript"
  # prettierを使用する場合は追加
  - "@vue/prettier"

rules:
  "vue/no-v-html": "off"
